### ISSUE TITLE
Adding script tag 

### ISSUE THREAD

**Issue by JestVA** [ndesmic/react-ssg#1]
Hi ndesmic,

Your project is sweet. How would you go about also adding a script tag say loading some analytics package if you wanted to do it when outputting the templates into html such that it is included in the head element?

**Comment by ndesmic** [comment]
There's a component for that: https://github.com/ndesmic/react-ssg/blob/main/templates/preact/components/_script.js

You'd use it like this: https://github.com/ndesmic/react-ssg/blob/main/templates/preact/_layout.preact.js#L13

**Comment by JestVA** [comment]
Thanks for the pointer. Glad you've covered it :)

**Comment by JestVA** [comment]
One more question: Do you think this could work with components loaded with `loadable-components` (lib for lazy loading React) because I have some deps in these components that need the window object.. a thing called `btoa`. And how does the renderer handle style? Can it use CSS-in-JS from these components loaded with loadable components (Emotion). Basically not sure how the style is still there for something rendered on the server but only working once we have a client browser.

**Comment by ndesmic** [comment]
> One more question: Do you think this could work with components loaded with `loadable-components` (lib for lazy loading React) because I have some deps in these components that need the window object.. a thing called `btoa`. And how does the renderer handle style? Can it use CSS-in-JS from these components loaded with loadable components (Emotion). Basically not sure how the style is still there for something rendered on the server but only working once we have a client browser.

If it's not a build-level step it should be handled just fine.  window access is fine, it works in modules.  CSS-in-JS likely won't work because it requires a bundler to deal with the imports to non-JS files but Chrome should be adding support for true CSS modules and such soon.
